Repository hashicorp/consul-terraform-sync, pull requests merged in 2020-10, with the labels that each got.

#117 Return version before processing config files
  cli.go
Labels: bug

#113 Reference official config docs on consul website
  README.md
  docs/config.md
Labels: documentation

#121 set default retry count
  driver/terraform.go
Labels: bug

#120 HCL marshal services variable
  go.mod
  go.sum
  templates/tftmpl/template_funcs.go
  templates/tftmpl/template_funcs_test.go
  templates/tftmpl/testdata/terraform.tfvars.tmpl
  templates/tftmpl/tfvars.go
Labels: enhancement

#124 Inspect mode
  cli.go
  client/terraform_cli.go
  config/task.go
  controller/controller.go
  controller/controller_test.go
  controller/readonly.go
  controller/readonly_test.go
  controller/readwrite.go
  controller/readwrite_test.go
  driver/driver.go
  driver/task.go
  driver/task_test.go
  driver/terraform.go
  mocks/driver/driver.go
  templates/tftmpl/root.go
Labels: enhancement

#129 Expand usage of Terraform backends for state store
  config/terraform.go
  config/terraform_test.go
  controller/controller.go
  templates/tftmpl/root_test.go
Labels: enhancement

#130 Capture data on process of updating network infrastructure in `Event`
  controller/controller.go
  controller/readwrite.go
  controller/readwrite_test.go
  driver/task.go
  driver/task_test.go
  event/event.go
  event/event_test.go
  go.mod
Labels: enhancement

#131 Configurable Terraform version and v0.14 support
  config/config_test.go
  config/driver_test.go
  config/terraform.go
  config/terraform_test.go
  controller/controller.go
  driver/terraform_download.go
  driver/terraform_download_test.go
  examples/sync-tasks/my-task/main.tf
  templates/tftmpl/root.go
  templates/tftmpl/root_test.go
  templates/tftmpl/testdata/main.tf
  version/terraform.go
  version/terraform_test.go
Labels: enhancement
