Repository hashicorp/consul-terraform-sync, pull requests merged in 2021-04, with the labels that each got.

#242 Add retry when hcat connection with Consul has an issue
  controller/readwrite.go
  controller/watcher.go
  e2e/benchmarks/services_test.go
  e2e/benchmarks/task_trigger_test.go
  e2e/benchmarks/tasks_concurrent_test.go
  e2e/benchmarks/tasks_test.go
  e2e/e2e_test.go
  go.mod
  go.sum
  retry/retry.go
  retry/retry_test.go
  testutils/consul.go
Labels: bug

#250 Fix api-serve unit test race condition retry
  api/api_test.go
Labels: bug

#253 Add more documentation around e2e and benchmarks
  e2e/README.md
  e2e/api_test.go
  e2e/benchmarks/services_test.go
  e2e/benchmarks/task_trigger_test.go
  e2e/benchmarks/tasks_concurrent_test.go
  e2e/benchmarks/tasks_test.go
  e2e/command_test.go
  e2e/e2e_test.go
  e2e/render_test.go
  e2e/tasks_test.go
Labels: documentation

#254 Support condition config in task blocks
  config/condition.go
  config/condition_catalog_services.go
  config/condition_catalog_services_test.go
  config/condition_services.go
  config/condition_services_test.go
  config/condition_test.go
  config/config.go
  config/config_test.go
  config/task.go
  config/task_test.go
  config/testdata/long.hcl
  config/testdata/long.json
Labels: enhancement

#257 update hcat version for render-complete race fix
  go.mod
  go.sum
Labels: backport/0.1, bug

#262 fix inspect mode log output
  command/cli.go
Labels: bug

#261 all but last consul retry log set to DEBUG level
  controller/watcher.go
Labels: enhancement

#263 tfexec security patch
  go.mod
  go.sum
Labels: backport/0.1, security

#265 Support catalog-services condition in templating
  controller/controller.go
  controller/controller_test.go
  driver/task.go
  driver/terraform.go
  go.mod
  go.sum
  templates/tftmpl/condition.go
  templates/tftmpl/golden_test.go
  templates/tftmpl/integration_test.go
  templates/tftmpl/root.go
  templates/tftmpl/template_funcs.go
  templates/tftmpl/testdata/terraform_cs.tfvars.tmpl
  templates/tftmpl/tfvars.go
Labels: enhancement

#268 Update tfvars map to use "key = value"
  examples/sync-tasks/my-task/terraform.tfvars
  examples/sync-tasks/my-task/terraform.tfvars.tmpl
  templates/tftmpl/testdata/only_api_service.tfvars
  templates/tftmpl/testdata/only_web_service.tfvars
  templates/tftmpl/testdata/terraform.tfvars
  templates/tftmpl/testdata/terraform.tfvars.tmpl
  templates/tftmpl/tfvars.go
Labels: enhancement

#271 Update fallback Terraform version from 0.13.5 to 0.13.7
  driver/terraform_download.go
Labels: backport/0.1, security
