Repository hashicorp/consul-terraform-sync, pull requests merged in 2021-09, with the labels that each got.

#371 Remove arm v5v6 build references
  docker/Dockerfile
Labels: backport/0.3

#378 Add schedule task condition configuration
  config/condition.go
  config/condition_schedule.go
  config/condition_schedule_test.go
  config/condition_test.go
  config/task.go
  config/task_test.go
  go.mod
  go.sum
Labels: enhancement

#381 Support running scheduled tasks
  controller/readwrite.go
  controller/readwrite_test.go
  driver/task.go
  driver/terraform.go
  e2e/condition_schedule_test.go
  e2e/condition_test.go
  templates/tftmpl/notifier/suppress_notification.go
  templates/tftmpl/notifier/suppress_notification_test.go
Labels: enhancement

#385 Issue 382 add regex monitor for schedule condition
  config/condition.go
  config/condition_catalog_services.go
  config/condition_catalog_services_test.go
  config/condition_consul_kv.go
  config/condition_consul_kv_test.go
  config/condition_schedule.go
  config/condition_services.go
  config/condition_services_test.go
  config/condition_test.go
  config/config.go
  config/config_test.go
  config/monitor.go
  config/monitor_catalog_services.go
  config/monitor_consul_kv.go
  config/monitor_services.go
  config/source_input.go
  config/source_input_services.go
  config/source_input_services_test.go
  config/source_input_test.go
  config/task.go
  config/task_test.go
  config/testdata/long.hcl
  config/testdata/long.json
  controller/controller.go
  controller/controller_test.go
  driver/task.go
  e2e/condition_schedule_test.go
  e2e/test_modules/consul_kv_file/main.tf
  e2e/test_modules/consul_kv_file/variables.tf
  e2e/test_modules/local_instances_file/main.tf
  e2e/test_modules/local_tags_file/main.tf
  e2e/test_modules/local_tags_file/variables.tf
  templates/tftmpl/condition.go
  templates/tftmpl/condition_catalog_services.go
  templates/tftmpl/condition_consul_kv.go
  templates/tftmpl/condition_consul_kv_test.go
  templates/tftmpl/condition_services.go
  templates/tftmpl/golden_test.go
  templates/tftmpl/monitor_catalog_services.go
  templates/tftmpl/monitor_consul_kv.go
  templates/tftmpl/monitor_services.go
  templates/tftmpl/root.go
  templates/tftmpl/root_test.go
  templates/tftmpl/source_input_services.go
  templates/tftmpl/testdata/terraform_services_source_input.tmpl
  templates/tftmpl/tfvars.go
Labels: enhancement

#394 updated changelog for logging changes
  CHANGELOG.md
Labels: backport/0.4

#397 Update CHANGELOG.md with 0.4.0 beta1 date
  CHANGELOG.md
Labels: backport/0.4

#400 update alpine version used in docker image
  docker/Dockerfile
Labels: security
