Repository hashicorp/consul-terraform-sync, pull requests merged in 2021-07, with the labels that each got.

#331 Add error when setting terraform_version config option per task in OSS
  config/config_test.go
  config/task.go
  config/task_test.go
Labels: enhancement

#333 Add support for Terraform v1.0
  examples/reference-example/sync-tasks/my-task/main.tf
  go.mod
  go.sum
  templates/tftmpl/root_test.go
  templates/tftmpl/testdata/catalog-services-condition/main_include.tf
  templates/tftmpl/testdata/main.tf
  version/terraform.go
  version/terraform_test.go
Labels: backport/0.2

#337 Fix handler to use http.Request context to react to client connection
  api/client.go
  api/task.go
  api/task_test.go
Labels: backport/0.1, backport/0.2, bug

#338 Refactor API server to stem from controller
  command/cli.go
  controller/controller.go
  controller/controller_test.go
  controller/readonly.go
  controller/readwrite.go
  controller/readwrite_test.go
  e2e/benchmarks/task_trigger_test.go
  e2e/benchmarks/tasks_concurrent_test.go
  e2e/render_test.go
Labels: backport/0.1, backport/0.2

#339 Remove intermediate struct units
  controller/controller.go
  controller/readonly.go
  controller/readonly_test.go
  controller/readwrite.go
  controller/readwrite_test.go
  driver/drivers.go
Labels: backport/0.1, backport/0.2

#349 Add config decode error wrapper
  config/config.go
  config/decode.go
  config/decode_test.go
Labels: enhancement
