Repository hashicorp/consul-terraform-sync, pull requests merged in 2021-01, with the labels that each got.

#165 Fix Consul KV path appending terraform suffix 2x
  client/terraform_cli.go
  config/terraform.go
  config/terraform_test.go
Labels: enhancement

#164 Update default transport configurations
  config/config_test.go
  config/testdata/long.hcl
  config/testdata/long.json
  config/transport.go
  go.sum
Labels: enhancement

#166 User defined metadata for services
  config/config_test.go
  config/service.go
  config/service_test.go
  controller/controller.go
  templates/tftmpl/integration_test.go
  templates/tftmpl/root.go
  templates/tftmpl/template_funcs.go
  templates/tftmpl/template_funcs_test.go
  templates/tftmpl/testdata/only_api_service.tfvars
  templates/tftmpl/testdata/only_web_service.tfvars
  templates/tftmpl/testdata/terraform.tfvars
  templates/tftmpl/testdata/variables.tf
  templates/tftmpl/tfvars.go
  templates/tftmpl/variables.go
Labels: enhancement

#167 Fix indefinite hanging when tasks have identical providers and services
  templates/tftmpl/golden_test.go
  templates/tftmpl/module_variables.go
  templates/tftmpl/root.go
  templates/tftmpl/testdata/main.tf
  templates/tftmpl/testdata/no_services.tfvars
  templates/tftmpl/testdata/only_api_service.tfvars
  templates/tftmpl/testdata/only_web_service.tfvars
  templates/tftmpl/testdata/terraform.tfvars
  templates/tftmpl/testdata/terraform.tfvars.tmpl
  templates/tftmpl/testdata/variables.module.tf
  templates/tftmpl/testdata/variables.tf
  templates/tftmpl/tfvars.go
  templates/tftmpl/variables.go
Labels: bug

#169 Remove deprecated provider block with special error handling
  config/config.go
  config/config_test.go
Labels: enhancement

#170 add auto-commit setting support to providers
  config/config.go
  config/config_test.go
  config/task_test.go
  handler/panos.go
  handler/panos_test.go
  templates/tftmpl/root.go
  templates/tftmpl/root_test.go
Labels: enhancement

#173 Add support for provider configuration containing object-type attributes
  templates/tftmpl/golden_test.go
  templates/tftmpl/integration_test.go
  templates/tftmpl/root.go
  templates/tftmpl/testdata/main.tf
  templates/tftmpl/testdata/variables.tf
Labels: bug

#174 include service kind in module input
  go.mod
  go.sum
  templates/tftmpl/template_funcs_test.go
  templates/tftmpl/testdata/only_api_service.tfvars
  templates/tftmpl/testdata/only_web_service.tfvars
  templates/tftmpl/testdata/terraform.tfvars
  templates/tftmpl/testdata/variables.tf
  templates/tftmpl/tfvars.go
  templates/tftmpl/variables.go
Labels: enhancement

#176 Update examples with new template
  examples/sync-tasks/my-task/main.tf
  examples/sync-tasks/my-task/terraform.tfvars
  examples/sync-tasks/my-task/terraform.tfvars.tmpl
  examples/sync-tasks/my-task/variables.module.tf
  examples/sync-tasks/my-task/variables.tf
Labels: documentation

#175 Support querying service by namespace
  go.mod
  go.sum
  templates/tftmpl/golden_test.go
  templates/tftmpl/integration_test.go
  templates/tftmpl/root.go
  templates/tftmpl/root_test.go
  templates/tftmpl/template_funcs.go
  templates/tftmpl/testdata/terraform.tfvars.tmpl
  templates/tftmpl/tfvars.go
Labels: bug, enhancement

#179 Add dirty to version output
  Makefile
  version/version.go
Labels: enhancement

#180 propagate context through handlers
  driver/terraform.go
  handler/fake.go
  handler/fake_test.go
  handler/handler.go
  handler/handler_test.go
  handler/panos.go
  handler/panos_test.go
Labels: enhancement

#178 simple, single retry for panos' commit
  handler/panos.go
  handler/panos_test.go
  retry/retry.go
Labels: enhancement
