Repository hashicorp/consul-terraform-sync, pull requests merged in 2021-11, with the labels that each got.

#475 Set CGO_ENABLED=0
  .github/workflows/build.yml
Labels: bug

#476 Not all diagnostics include context
  client/terraform_cli.go
Labels: bug

#484 Adding sign-linux-rpms event to ci.hcl
  .release/ci.hcl
Labels: backport/0.4

#483 Add 0.4.1 release to changelog for docker fix
  CHANGELOG.md
Labels: backport/0.4

#490 Add tls cli client
  api/client.go
  api/client_test.go
  api/server_test.go
  api/test.go
  command/cli.go
  command/meta.go
  command/task_disable.go
  command/task_enable.go
  go.mod
Labels: enhancement

#491 Use base version for GitDescribe for app to build version string
  .github/workflows/build.yml
  .release/docker/Makefile
  build-scripts/version.sh
Labels: bug

#508 Add config error for driver.terraform-cloud when using CTS OSS
  config/decode.go
  config/task.go
Labels: backport/0.4

#501 [RELENG-1025]: Update docker build to use docker build action
  .github/workflows/build.yml
  .release/docker/Makefile
  Dockerfile
Labels: backport/0.4

#461 Changelog v0.4.2
  CHANGELOG.md
Labels: backport/0.4

#517 Add known issue to changelog #516
  CHANGELOG.md
Labels: backport/0.4

#510 Add openapi and codegen
  api/api.go
  api/client.go
  api/dryrun.go
  api/handler.go
  api/middleware.go
  api/oapigen/readme.md
  api/oapigen/server.go
  api/oapigen/types.go
  api/openapi.yaml
  api/request_id.go
  api/task.go
  go.mod
  go.sum
  mocks/api/httpClient.go
  mocks/client/client.go
  mocks/client/terraformExec.go
  mocks/driver/driver.go
  mocks/handler/panosClient.go
  mocks/templates/resolver.go
  mocks/templates/template.go
  mocks/templates/watcher.go
Labels: enhancement

#524 Implement Services Condition & Source Input MetaData field
  driver/terraform.go
  driver/terraform_test.go
  e2e/condition_service_test.go
  templates/tftmpl/tmplfunc/hcl_service_func.go
  templates/tftmpl/tmplfunc/hcl_service_func_test.go
  templates/tftmpl/tmplfunc/services_meta.go
  templates/tftmpl/tmplfunc/services_meta_test.go
  templates/tftmpl/tmplfunc/tmpl_func.go
Labels: enhancement
