Repository hashicorp/consul-terraform-sync, pull requests merged in 2021-06, with the labels that each got.

#306 Run Terraform validate after initializing tasks
  client/client.go
  client/printer.go
  client/printer_test.go
  client/terraform_cli.go
  client/terraform_cli_test.go
  client/terraform_exec.go
  controller/controller.go
  controller/controller_test.go
  controller/readwrite_test.go
  driver/driver.go
  driver/terraform.go
  go.mod
  mocks/client/client.go
  mocks/client/terraformExec.go
  mocks/driver/driver.go
Labels: enhancement

#319 Store an event when a task becomes enabled and executes
  api/task.go
  api/task_test.go
Labels: bug

#325 added public roadmap details to README and contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation
