Repository hashicorp/consul-terraform-sync, pull requests merged in 2021-02, with the labels that each got.

#181 Set provider intermediate variable as sensitive
  driver/terraform.go
  driver/terraform_download.go
  templates/tftmpl/golden_test.go
  templates/tftmpl/integration_test.go
  templates/tftmpl/root.go
  templates/tftmpl/testdata/variables.tf
  templates/tftmpl/variables.go
  templates/tftmpl/variables_test.go
Labels: enhancement, security

#184 Fix task_env type validation
  config/provider.go
  config/provider_test.go
Labels: bug

#186 Refactor buffer_period to driver-level
  controller/controller.go
  controller/controller_test.go
  controller/readwrite.go
  driver/driver.go
  driver/task.go
  driver/terraform.go
  mocks/driver/driver.go
Labels: bug, enhancement

#187 Attempt to improve consul service templating flakiness
  templates/tftmpl/integration_test.go
Labels: bug

#189 Consume `enabled` field in task driver
  controller/controller.go
  controller/controller_test.go
  driver/task.go
  driver/terraform.go
  driver/terraform_test.go
  e2e/config.go
  e2e/e2e_test.go
Labels: enhancement

#194 Support disable CLI
  cli.go
  command/commands.go
  command/meta.go
  command/task_disable.go
  go.mod
Labels: enhancement

#197 command: add port flag option
  command/commands.go
  command/meta.go
  command/task_disable.go
  config/config.go
Labels: enhancement

#198 Support enable task CLI command
  command/commands.go
  command/meta.go
  command/task_enable.go
Labels: enhancement

#202 Update Task Status API to support enabled/disabled tasks
  api/api.go
  api/api_test.go
  api/client_test.go
  api/task_status.go
  api/task_status_test.go
  controller/readwrite.go
  controller/readwrite_test.go
  e2e/api_test.go
  e2e/config.go
Labels: enhancement

#203 Update Overall Status API to support enabled/disabled tasks
  api/api.go
  api/api_test.go
  api/client_test.go
  api/overall_status.go
  api/overall_status_test.go
  api/task_status_test.go
  e2e/api_test.go
Labels: enhancement

#205 Add task name to update API logs
  api/api.go
  api/task.go
Labels: enhancement

#207 update hashicat to latest version
  go.mod
  go.sum
Labels: enhancement

#213 Use consul configuration for the default consul backend for Terraform
  config/consul.go
  config/terraform.go
  config/tls.go
  controller/controller.go
  controller/controller_test.go
  driver/task.go
  driver/terraform.go
Labels: bug

#215 initial dockerfile and entrypoint
  docker/Dockerfile
  docker/docker-entrypoint.sh
Labels: enhancement

#216 fix docker permissions with a 'home' directory
  docker/Dockerfile
Labels: bug
