Repository hashicorp/consul-terraform-sync, pull requests merged in 2022-03, with the labels that each got.

#740 upgraded hcat
  go.mod
  go.sum
Labels: bug

#739 Update CHANGELOG.md
  CHANGELOG.md
Labels: backport/0.5

#741 Wait for task to be inactive before running
  controller/readwrite.go
  controller/readwrite_test.go
  e2e/e2e_test.go
  e2e/utils.go
Labels: backport/0.5

#746 Create instance files only after initial delay
  e2e/e2e_test.go
  e2e/test_modules/delayed_module/main.tf
Labels: backport/0.5

#748 Handle missing tf state
  client/terraform_cli.go
  client/terraform_cli_test.go
Labels: bug

#749 Wait longer for API to start
  api/api_test.go
Labels: backport/0.5

#752 Stop scheduled task as soon as task is deleted
  controller/readwrite.go
  controller/readwrite_test.go
  controller/server.go
Labels: backport/0.5

#762 Temporarily turn off NVD sec scanning
  .release/security-scan.hcl
Labels: backport/0.3, backport/0.4, backport/0.5

#763 Update CHANGELOG.md
  CHANGELOG.md
Labels: backport/0.5
