Repository hashicorp/consul-terraform-sync, pull requests merged in 2022-01, with the labels that each got.

#575 Replace deprecated 'circleci/golang' with 'cimg/go' image
  .circleci/config.yml
Labels: backport/0.4

#602 Remove ECR Docker repository
  .github/workflows/build.yml
Labels: backport/0.4

#535 Fix query types to use blocking queries
  controller/controller_test.go
  controller/readonly_test.go
  controller/readwrite.go
  controller/readwrite_test.go
  controller/server_test.go
  driver/driver.go
  driver/drivers.go
  driver/terraform.go
  driver/terraform_test.go
  go.mod
  go.sum
  mocks/driver/driver.go
  mocks/templates/watcher.go
  templates/hcat.go
  templates/tftmpl/tmplfunc/catalog_services_registration.go
  templates/tftmpl/tmplfunc/services_regex.go
Labels: bug

#608 Add new configuration type ModuleInputConfigs
  config/condition_schedule.go
  config/module_input.go
  config/module_input_test.go
  config/monitor.go
  config/monitor_catalog_services.go
  config/monitor_consul_kv.go
  config/monitor_no.go
  config/monitor_services.go
Labels: enhancement

#610 Update TaskConfig with new ModuleInputConfigs
  api/representation.go
  api/representation_test.go
  config/config_test.go
  config/module_input.go
  config/module_input_test.go
  config/task.go
  config/task_test.go
  config/testdata/long.hcl
  config/testdata/long.json
  controller/controller.go
  controller/controller_test.go
  controller/server.go
  driver/task.go
  driver/task_test.go
  driver/terraform.go
  driver/terraform_test.go
Labels: enhancement

#612 Update Notifiers to support Module Inputs with Other Condition Types
  driver/terraform.go
  driver/terraform_test.go
  e2e/condition_schedule_test.go
  e2e/module_input_test.go
  templates/tftmpl/notifier/catalog_services_registration.go
  templates/tftmpl/notifier/catalog_services_registration_test.go
  templates/tftmpl/notifier/consul_kv.go
  templates/tftmpl/notifier/consul_kv_test.go
  templates/tftmpl/notifier/services.go
  templates/tftmpl/notifier/services_test.go
  templates/tftmpl/notifier/suppress_notification.go
Labels: enhancement

#629 Remove consul dep
  config/condition.go
  config/config.go
  config/module_input.go
  go.mod
  go.sum
  internal/decode/decode.go
  internal/decode/decode_test.go
Labels: backport/0.2, backport/0.3, backport/0.4

#636 Sequential E2E Tests for Local Runs
  Makefile
  api/representation_test.go
  controller/server_test.go
  e2e/api_test.go
  e2e/command_test.go
  e2e/command_tls_test.go
  e2e/condition_catalog_service_test.go
  e2e/condition_consul_kv_test.go
  e2e/condition_schedule_test.go
  e2e/condition_service_test.go
  e2e/e2e_test.go
  e2e/module_input_test.go
  e2e/tasks_test.go
  e2e/utils.go
Labels: enhancement
