Repository hashicorp/consul-terraform-sync, pull requests merged in 2022-02, with the labels that each got.

#653 Cleanup and Test Improvements
  api/api.go
  api/api_test.go
  api/client.go
  api/representation_test.go
  api/response_writers.go
  api/server_test.go
  api/task.go
  api/task_create_test.go
  api/task_lifecycle_client.go
  api/task_status.go
  api/task_status_test.go
  api/test.go
  command/cli.go
  docker/Dockerfile
  e2e/api_test.go
  e2e/command_test.go
  e2e/command_tls_test.go
  e2e/compatibility/consul_test.go
  e2e/condition_consul_kv_test.go
  e2e/e2e_test.go
  e2e/tasks_test.go
  e2e/utils.go
Labels: enhancement

#663 API Client Improvements and Tests
  api/client.go
  api/client_test.go
Labels: enhancement

#661 Updates to cli ux
  api/task_lifecycle_client.go
  command/cli.go
  command/commands.go
  command/meta.go
  command/task_create.go
  command/task_delete.go
  command/task_enable.go
  e2e/command_test.go
  e2e/command_tls_test.go
  logging/logging.go
Labels: enhancement

#665 Client Refactoring and Testing
  api/client.go
  api/client_test.go
  api/server_test.go
  api/task_lifecycle_client.go
  api/test.go
  command/cli.go
  command/meta.go
Labels: enhancement

#672 Fix issue: 'service' block deprecation is logged even when not configured
  config/config.go
Labels: bug

#681 Get Task API
  api/oapigen/client.go
  api/oapigen/server.go
  api/openapi.yaml
  api/task.go
  api/task_create_test.go
  api/task_delete.go
  api/task_delete_test.go
  api/task_get.go
  api/task_get_test.go
  e2e/api_test.go
Labels: enhancement

#682 Create task module no exist error
  controller/readwrite.go
  controller/server.go
  controller/server_test.go
  driver/drivers.go
  e2e/command_test.go
Labels: bug

#694 Handle when CatalogService condition NodeMeta is nil in representation
  api/representation.go
  api/representation_test.go
Labels: bug

#692 Fix issue in Get Task API for services field as condition
  api/representation.go
  api/representation_test.go
  e2e/api_test.go
  e2e/e2e_test.go
Labels: bug

#695 Added `additionalProperties: false` to all objects in openapi.yaml
  api/middleware_test.go
  api/oapigen/server.go
  api/openapi.yaml
  api/task_create_test.go
  e2e/api_test.go
Labels: backport/0.5

#697 Clarify that infrastructure is not destroyed on task deletion
  command/meta.go
  command/task_delete.go
Labels: backport/0.5

#705 Hanging trigger issue
  controller/readwrite.go
  controller/server_test.go
  driver/driver.go
  driver/terraform.go
  mocks/driver/driver.go
  templates/tftmpl/notifier/catalog_services_registration.go
  templates/tftmpl/notifier/consul_kv.go
  templates/tftmpl/notifier/notifier.go
  templates/tftmpl/notifier/notifier_test.go
  templates/tftmpl/notifier/services.go
  templates/tftmpl/notifier/suppress_notification.go
Labels: backport/0.5

#707 [Part 1] E2E tests for creating a task with a shared dependency
  api/task_lifecycle_client.go
  e2e/condition_catalog_service_test.go
  e2e/condition_consul_kv_test.go
  e2e/config.go
Labels: backport/0.5

#712 [Part 2] E2E tests for creating a task with a shared dependency
  e2e/condition_catalog_service_test.go
  e2e/condition_consul_kv_test.go
  e2e/condition_schedule_test.go
  e2e/condition_service_test.go
Labels: backport/0.5

#452 Update changelog v0.5.0
  CHANGELOG.md
Labels: backport/0.5

#719 ld-flag-fix
  .github/workflows/build.yml
Labels: backport/0.2, backport/0.3, backport/0.4, backport/0.5

#718 Check that created task triggers as expected
  e2e/condition_catalog_service_test.go
Labels: backport/0.5

#724 Update bulk services function to skip health check
  testutils/consul.go
Labels: backport/0.4, backport/0.5

#729 Refactor required providers in controller
  CHANGELOG.md
  controller/controller.go
  controller/server_test.go
Labels: backport/0.5

#699 Do not merge - add post-publish events to ci.hcl
  .release/ci.hcl
Labels: backport/0.2, backport/0.3, backport/0.4, backport/0.5
